### PR TITLE
simplified qsub call, fixed kill, added working dir option + some tests

### PR DESCRIPTION
**Pull request by nantonel**
Addressing #151 #152 #103

### CODE REVIEW

**Comment by Moelf** [comment]
this is great, I hope someone review this

**Comment by bjarthur** [comment]
thanks!

**Comment by kescobo** [comment]
Can add the links manually in the sidebar too :+1: thanks for doing it!

**Comment by Moelf** [comment]
```
julia> addprocs_sge(5;queue=`-l h_vmem=4G,tmem=4G`, wd=mktempdir())
Unable to run job: unknown resource "tmem".
Exiting.
Error launching workers
ErrorException("")
Int64[]
```

I think this PR broke previously working version for out SGE

**Pull request merged**
