### PR TITLE
Explicitly set maximal virtual memory limit=10.1G, to avoid SGE abort…

### PR DESCRIPTION
**Pull request by cth**
…ing 64bit Julia process

All my jobs was being aborted by the cluster and it turns out that (64 bit) Julia pre-allocates A LOT of memory [(8 GB)](https://github.com/JuliaLang/julia/blob/e1d6e56a0781e1c453d541b87ab2cfbc14c364c1/src/gc.c#L88). and was being being shutdown for violating vmem limits 

This small patch checks if it is the 64bit version of Julia, and if so, set a hard vmem limit to 10.1G.

For me, this solves the problem and makes it possible for me successfully call `addprocs_sge`

On the flipside, if Julia ends up consuming more virtual memory, then it will be shutdown. However, I think the 10GB pre-allocated is already a fairly generous amount. Note that it is 10GB per parallel process: On a 64 core processor this is already more than half a TB. Hence, if the limit was to be increased, that can adversely limit how many Julia processes that can be spawned on a given host.

### CODE REVIEW

**Comment by jiahao** [comment]
lgtm

**Comment by floswald** [comment]
not sure we want this as a general solution. I use `-l h_vmem=4G, tmem=4G` on a cluster with julia 0.5-rc3 and that works. by default requesting 10G would put me on a significantly longer queue. As you say, *On a 64 core processor this is already more than half a TB*, which system administrator would allow you to reserve that amount of memory? given that every system is slightly different in this respect, I think we need a way to just pass those parameters as arguments. note: doing 
```julia
addprocs_sge(20, qsub_env = "-l h_vmem=4G, tmem=4G")
```
didn't work for me (although I can't really see why it shouldnt).

**Comment by floswald** [comment]
I think #44 is better for this issue.

**Comment by bjarthur** [comment]
given #44 can we close this?

**Comment by cth** [comment]
Yes, I agree that this is a better solution

**Pull request closed without merging**
