### PR TITLE
add support for cookie changes

### PR DESCRIPTION
**Pull request by amitmurthy**
ref : https://github.com/JuliaLang/julia/pull/16423

### CODE REVIEW

**Comment by amitmurthy** [comment]
@andreasnoack could you please test this on any cluster you may have access to and merge?

**Comment by andreasnoack** [comment]
I've tested with SGE and Slurm which are the managers I've access to. It works so I'll merge. If there are  issues with other managers then people can open specific issues. Thanks for fixing this.

**Comment by bjarthur** [comment]
does NOT work for me!  gives as 'invalid version string" ERROR:

```
julia> addprocs_sge(3)
job id is 50808835, waiting for job to start ....................................
Worker 5 terminated.
Worker 6 terminated.ERROR (unhandled task failure): ArgumentError: invalid version string: 

ERROR (unhandled task failure): ArgumentError: invalid version string: 
	From worker 6:	Master process (id 1) could not connect within 60.0 seconds.
	From worker 6:	exiting.
Worker 7 terminated.
ERROR (unhandled task failure): ArgumentError: invalid version string: 
 in VersionNumber(::String) at ./version.jl:91
 in process_hdr(::TCPSocket, ::Bool) at ./multi.jl:1054
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:994
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at ./multi.jl:985
 in (::Base.##299#300{TCPSocket,TCPSocket,Bool})() at ./event.jl:46
```

**Comment by amitmurthy** [comment]
What are the versions of Julia on the master and the workers? Are they the same or different?

**Comment by bjarthur** [comment]
last night's nightly on both.  Version 0.5.0-dev+4445

**Comment by bjarthur** [comment]
nevermind.  works fine when running julia on a compute node.  problem was that i forgot to qlogin and was on the login node.  not sure why that would make a difference.  but it works.

interesting thought that the "invalid version string" seems to be what is thrown when there is a timeout error.

**Comment by amitmurthy** [comment]
The wrong error message needs to be fixed. Good catch.

**Pull request merged**
