### PR TITLE
Cleanup Slurm job files at exit

### PR DESCRIPTION
**Pull request by lstagner**
I was getting annoyed at all job files. So this PR has julia automatically remove the Slurm job files at exit.

### CODE REVIEW

**Comment by bjarthur** [comment]
i don't use slurm, but i wonder, would it be a problem if old files are still there and you don't delete them before adding new jobs?

**Comment by lstagner** [comment]
I don't know. I do know that the all the old job files were already being deleted before new job files were created. This PR just changes when the files get deleted.

**Comment by vchuravy** [comment]
If a job fails I is important to preserve the output. I think that is why delete at start vs delete at end was used.

**Comment by lstagner** [comment]
That is a valid concern. I could separate the standard output and error streams so we would only delete the output files and empty error files.

**Pull request closed without merging**
