### PR TITLE
make Julia 0.7 compatible

### PR DESCRIPTION
**Pull request by tanmaykm**
- updated for Julia 0.7+
- dropped support for older Julia versions
- enabled basic CI on travis
- updated ElasticManager for 0.7 changes

### CODE REVIEW

**Comment by tanmaykm** [comment]
ref: #93

**Comment by tanmaykm** [comment]
Tested ElasticManager to be working. But I don't have a way to test other managers. Package loads though, and I do not see anything else obvious that may break.

Will merge and tag this in a bit.

**Comment by kaskarn** [comment]
Tried to use the package this morning (for use with SLURM); it seems to fail during precompilation (maybe missing a `using Distributed` somewhere?). 

```
(v1.0) pkg> update
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

julia> using ClusterManagers
[ Info: Precompiling ClusterManagers [34f1f09b-3a8b-5176-ab39-66d58a4d544e]
WARNING: could not import Base.launch into ClusterManagers
WARNING: could not import Base.manage into ClusterManagers
WARNING: could not import Base.init_worker into ClusterManagers
WARNING: could not import Base.connect into ClusterManagers
ERROR: LoadError: LoadError: syntax: extra token "PBSManager" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /nas/longleaf/home/baldassa/.julia/packages/ClusterManagers/3HQoS/src/ClusterManagers.jl:3
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:389
 [12] top-level scope at ./none:3
in expression starting at /nas/longleaf/home/baldassa/.julia/packages/ClusterManagers/3HQoS/src/qsub.jl:3
in expression starting at /nas/longleaf/home/baldassa/.julia/packages/ClusterManagers/3HQoS/src/ClusterManagers.jl:19
ERROR: Failed to precompile ClusterManagers [34f1f09b-3a8b-5176-ab39-66d58a4d544e] to /nas/longleaf/home/baldassa/.julia/compiled/v1.0/ClusterManagers/2gedf.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834

```

**Comment by kaskarn** [comment]
Looks like it just got merged; all seems well, thank you!

```
julia> Pkg.update()
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed ClusterManagers â v0.3.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [34f1f09b] â ClusterManagers v0.2.0 â v0.3.0
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [34f1f09b] â ClusterManagers v0.2.0 â v0.3.0

julia> using ClusterManagers
[ Info: Precompiling ClusterManagers [34f1f09b-3a8b-5176-ab39-66d58a4d544e]
```

**Comment by kaskarn** [comment]
Must have jinxed it -- slurm.jl file has some deprecated calls (Base.Distributed function moved to Distributed in 0.7, and a couple other things like a deprecated call to filter() ). I can look and make a PR later, but if I can't sort it out I'll add detail here, or create an issue, as you prefer.

**Comment by tanmaykm** [comment]
Sure!

**Pull request merged**
