### PR TITLE
Update command line cookie specification

### PR DESCRIPTION
**Pull request by amitmurthy**
Change `--worker <cookie>` to `--worker=<cookie>` in light of  https://github.com/JuliaLang/julia/pull/22114

### CODE REVIEW

**Comment by amitmurthy** [comment]
This should not have an effect on Julia versions older than https://github.com/JuliaLang/julia/pull/22114 as `--worker=<cookie>` is a valid format for mandatory args too.

**Comment by sbromberger** [comment]
@amitmurthy - how does one now use stdin for cookies?

**Comment by amitmurthy** [comment]
ClusterManagers will have to be changed to write the cookie to an appropriate stdin. Like is being done here - https://github.com/JuliaLang/julia/blob/5e21673e504380b2dcb3f90c39464e59d6f617ea/base/distributed/managers.jl#L203 . `write_cookie(io)` is defined as `write(io.in, string(cluster_cookie(), "\n"))`

However I just realized that in 0.7, `open` only returns a `Process` object and that needs to be fixed too. Will update this PR in a while.

**Comment by amitmurthy** [comment]
Merging this as is for now. Will update for 0.7 changes later.

**Comment by sbromberger** [comment]
Thank you for all the help on this!!

**Comment by sbromberger** [comment]
@amitmurthy sorry - just looping back on this. I'm having difficulty understanding what I need to change here to get slurm to use stdin for the cookies. Any help would be greatly appreciated.

**Comment by amitmurthy** [comment]
https://computing.llnl.gov/tutorials/ibm_sp/man/srun.txt states that by default stdin is broadcast from the controlling terminal to all workers. So, the following should work with Julia 0.7 :

```
--- a/src/slurm.jl
+++ b/src/slurm.jl
@@ -41,8 +41,10 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
 
         np = manager.np
         jobname = "julia-$(getpid())"
-        srun_cmd = `srun -J $jobname -n $np -o "job%4t.out" -D $exehome $(srunargs) $exename $exeflags $worker_arg`
-        out, srun_proc = open(srun_cmd)
+        srun_cmd = `srun -J $jobname -n $np -o "job%4t.out" -D $exehome $(srunargs) $exename $exeflags --worker`
+        io = open(srun_cmd, "r+")
+        Base.Distributed.write_cookie(io)
+
         for i = 0:np - 1
             print("connecting to worker $(i + 1) out of $np\r")
             local w=[]
@@ -67,7 +69,7 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
                 config.host = strip(w[2])
                 # Keep a reference to the proc, so it's properly closed once
                 # the last worker exits.
-                config.userdata = srun_proc
+                config.userdata = io
                 push!(instances_arr, config)
                 notify(c)
             end
```

The above patch also handles the change that in 0.7 `open` no longer returns a tuple.

If you can test this out and then open a PR, that would be great.

**Comment by sbromberger** [comment]
```
julia> addprocs(SlurmManager(4), N=4, partition="pdebug", t="00:5:00")
Error launching Slurm job:
ERROR (unhandled task failure): ArgumentError: mode must be "r" or "w", not "r+"
ERROR: ArgumentError: mode must be "r" or "w", not "r+"
Stacktrace:
 [1] wait(::Task) at ./task.jl:184
 [2] #addprocs_locked#30(::Array{Any,1}, ::Function, ::ClusterManagers.SlurmManager) at ./distributed/cluster.jl:361
 [3] (::Base.Distributed.#kw##addprocs_locked)(::Array{Any,1}, ::Base.Distributed.#addprocs_locked, ::ClusterManagers.SlurmManager) at ./<missing>:0
 [4] #addprocs#29(::Array{Any,1}, ::Function, ::ClusterManagers.SlurmManager) at ./distributed/cluster.jl:319
 [5] (::Base.Distributed.#kw##addprocs)(::Array{Any,1}, ::Base.Distributed.#addprocs, ::ClusterManagers.SlurmManager) at ./<missing>:0
```

I'm still on 0.6, though, if that matters...

**Comment by sbromberger** [comment]
Also, no `Base.Distributed.write_cookie` in 0.6, I guess.

I won't be able to run 0.7 on this cluster for a while.

**Comment by amitmurthy** [comment]
Assuming slurm by default broadcasts stdin from the controlling terminal to all workers, this should work with 0.6

```
--- a/src/slurm.jl
+++ b/src/slurm.jl
@@ -41,8 +41,10 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
 
         np = manager.np
         jobname = "julia-$(getpid())"
-        srun_cmd = `srun -J $jobname -n $np -o "job%4t.out" -D $exehome $(srunargs) $exename $exeflags $worker_arg`
-        out, srun_proc = open(srun_cmd)
+        srun_cmd = `srun -J $jobname -n $np -o "job%4t.out" -D $exehome $(srunargs) $exename $exeflags -e 'Base.start_worker(readline())'`
+        srun_stdin, srun_proc = open(srun_cmd, "w")
+        println(srun_stdin, Base.Distributed.cluster_cookie())
+
         for i = 0:np - 1
             print("connecting to worker $(i + 1) out of $np\r")
             local w=[]
```

**Comment by sbromberger** [comment]
I'll give it a try in a few. @amitmurthy - thanks again for all your help with this.

**Comment by sbromberger** [comment]
This appears to work. The worker processes are showing up as
```
seth     127358 127352  1 08:13 ?        00:00:01 /g/g17/seth/dev/julia/bin/julia -e Base.start_worker(readline())
```
Which doesn't have the cookie anywhere in view. :)

**Comment by sbromberger** [comment]
Is this something that is only relevant to my environment or is it PR-worthy?

**Comment by amitmurthy** [comment]
I suppose a PR will be good - other environments may have similar security considerations.

**Comment by sbromberger** [comment]
Ref: #77

**Pull request merged**
