### PR TITLE
[Slurm] Add sleep while waiting for job to start

### PR DESCRIPTION
**Pull request by David96**
See #173

### CODE REVIEW

**Review by kescobo — APPROVED** [review]
Seems like a good thing to me. I'll leave it for a day or two and then merge if there are no objections

**Comment by David96** [comment]
I think @DrChainsaw 's idea (having an iterator supplying the wait times) is way nicer than this. Depending on what you prefer we can leave this open and I'll update it to that approach as soon as I find time or you can merge it as is and I'll create a new pull request when I get around to implementing it.

**Comment by kescobo** [comment]
I agree that's way nicer, and would be happy to accept a PR that implements it. Depending on how long you think it will take though, I'd be fine to merge this as a stop-gap.

**Comment by David96** [comment]
If it doesn't turn out to be unexpectedly difficult I should be able to do so next week.

**Pull request merged**
